### ISSUE TITLE
mcl login登录，验证码通过后，提示还需要进行“账户安全认证“的设备锁验证，但该认证链接打开后是空页面。 （我已经提前把这个号的所有安全机制关了）

### ISSUE THREAD

**Issue by Ru0ch3n** [mzdluo123/TxCaptchaHelper#6]
mcl login登录，验证码通过后，提示还需要进行“账户安全认证“的设备锁验证，但该认证链接打开后是空页面。 （我已经提前把这个号的所有安全机制关了）
![image](https://user-images.githubusercontent.com/47513906/127804514-d5d08523-ad6b-41a3-b810-575e1e5286f2.png)
![image](https://user-images.githubusercontent.com/47513906/127804542-75c11b25-4931-40c0-8d7f-df8d3f472b62.png)
请问这是为什么，可以怎样解决，谢谢！

**Comment by mzdluo123** [comment]
请看论坛公告栏

**Comment by Ru0ch3n** [comment]
想问个zz问题，是哪个论坛呢？能贴下链接吗，感谢Orz

**Comment by JMFANS** [comment]
> 想问个zz问题，是哪个论坛呢？能贴下链接吗，感谢Orz

你好，请问解决了吗，我打得开网页，但进去就是404 orz
