### ISSUE TITLE
能不能出个SDK

### ISSUE THREAD

**Issue by lz1998** [mzdluo123/TxCaptchaHelper#9]
想嵌入其他APP （[Go-Mirai-Client-Android](https://github.com/ProtobufBot/Go-Mirai-Client-Android)）

希望调用 `Helper.processCaptcha("http://xxx")` 时自动弹出窗口，等处理完成后返回 ticket，或抛出异常

**Comment by mzdluo123** [comment]
这么简单的接口不需要sdk也能很快写出来吧
